[package]
name = "hyu-vpn-macos-service"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
hyu-vpn-core = { path = "../../crates/hyu-vpn-core" }
hyu-vpn-daemon = { path = "../../crates/hyu-vpn-daemon" }
hyu-vpn-platform-macos = { path = "../../crates/hyu-vpn-platform-macos" }
hyu-vpn-protocol = { path = "../../crates/hyu-vpn-protocol" }
libc.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
